name: Deploy Smoke Test
on:
    workflow_dispatch:

jobs:
  postman_test:
      runs-on: ubuntu-latest
      
      steps:
      - name: Use variables
        run: |
          echo "branch name : $GITHUB_REF_NAME"
          echo "full branch name : $GITHUB_REF"

      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Install Newman
        run: |
            npm install -g newman
            npm install -g newman-reporter-htmlextra

      - name: Copy File
        run: cp ./postman/upload.csv $GITHUB_WORKSPACE
                
      - name: Run Postman Collection
        run: newman run "./postman/Virtual Agent.postman_collection.json" -r htmlextra

      - name: Publish report
        uses: actions/upload-artifact@v2
        with:
          name: newman-report
          path: ./newman        
