name: Newman CLI Sample Run
on:
    workflow_dispatch:

jobs:
    postman_test:
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: Install Newman
          run: |
              npm install -g newman
              npm install -g newman-reporter-htmlextra

        - name: Copy File
          run: cp ./postman/chat.csv $GITHUB_WORKSPACE
                  
        - name: Run Postman Collection
          run: newman run "./postman/Virtual Agent.postman_collection.json" -r htmlextra --reporter-htmlextra-export docs/index.html || true

          # Configure Git for the workflow
        - name: Set up Git
          run: |
            git config --global user.email "tlazelle@callpotential.com"
            git config --global user.name "Tom LaZelle"

   # Commit and push the report to the "gh-pages" branch
        - name: Commit and Push Report
          run: |
          git checkout gh-pages  # Switch to the "gh-pages" branch
          cp docs/index.html ./  # Copy the HTML report to the root of the branch
          git add report.html
          git commit -m "Add Newman report"
          git push origin gh-pages  # Push to the "gh-pages" branch
     