---
    name: Newman CLI Sample Run
    on:
        workflow_dispatch:
    
    jobs:
      newman:
        name: Run collections + tests with Newman
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master    
          - uses: SimonScholz/postman-newman-action@v1.0.0
            with:
              collection: https://api.postman.com/collections/29172423-25d47615-fc8b-477a-bb10-33d4ceabe5f1?access_key=PMAT-01HCJF6YMXGPFTBSB6TF6BBBHR
              envVar: '[{"key":"users","value":"zombie"}]'
    