name: Newman CLI Sample Run
on:
    workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  postman_test:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Install Newman
        run: |
            npm install -g newman
            npm install -g newman-reporter-htmlextra

      - name: Copy File
        run: cp ./postman/chat.csv $GITHUB_WORKSPACE
                
      - name: Run Postman Collection
        run: newman run "./postman/Virtual Agent.postman_collection.json" -r htmlextra --reporter-htmlextra-export ./newman/index.html

      - name: Publish report
        uses: actions/upload-artifact@v3
        with:
            name: newman-report
            path: ./newman/index.html
            retention-days: 1
      - name: saver
        run: mv ./newman/index.html /docs/index.html